name: Comment when changes requested

on: workflow_call

jobs:
  comment:
    name: Comment when changes requested
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v9
        with:
          workflow: comment_when_changes_requested_trigger.yml
          name: event_data
          allow_forks: true
      - name: Output pull request
        id: output_event_data
        run: echo event_data=$(<./event_data.json) >> $GITHUB_OUTPUT
      - name: Create comment file
        run: |
          cat << EOF > ./comment.txt
          @${{ fromJSON(steps.output_event_data.outputs.event_data).pull_request.user.login }}
          ${{ fromJSON(steps.output_event_data.outputs.event_data).review.user.login }} requested you to make some changes. Once you make changes, please re-request ${{ fromJSON(steps.output_event_data.outputs.event_data).review.user.login }} to review by clicking "re-request review" button 🔄 (located in the reviewers list on the right side of this page).
          EOF
      - name: Post comment
        run: gh pr comment ${{ fromJSON(steps.output_event_data.outputs.event_data).pull_request.number }} --body-file ./comment.txt --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}