name: Request review

on:
  workflow_call:
    inputs:
      reviewer:
        description: Reviewer's GitHub username
        required: true
        type: string

jobs:
  request_review:
    name: Request a review for the pull request to ${{ inputs.reviewer }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v10
        with:
          workflow: request_review_trigger.yml
          name: event_data
          allow_forks: true
      - name: Output pull request
        id: output_event_data
        run: echo event_data=$(<./event_data.json) >> $GITHUB_OUTPUT
      - name: Request a review for the pull request to ${{ inputs.reviewer }}
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/pulls/${{ fromJSON(steps.output_event_data.outputs.event_data).number }}/requested_reviewers \
          -f "reviewers[]=${{ inputs.reviewer }}"
        env:
          GH_TOKEN: ${{ github.token }}